name: eventstateprocessor
description: A Flutter package that wrap flutter bloc package for clearer implementation
version: 0.0.1
homepage: https://github.com/extremevn/event_state_processor

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
